### ISSUE TITLE
S_f1_norm and S_f2_norm

### ISSUE THREAD

**Issue by ChiCheng45** [oziogos/pyAOMlite#2]
in the method Sab both S_f1_norm and S_f2_norm are calculated but unused why is this?

**Comment by oziogos** [comment]
these are for a potential sanity check. If everything works as it should, both variables should be equal to 1.0

**Comment by ChiCheng45** [comment]
in that case maybe the extra calculation should be skipped unless a debug mode is switched on

**Comment by ChiCheng45** [comment]
I just saw in the latest you have commented them out, lets close this
